apiVersion: apps/v1
kind: Deployment
metadata:
  name: giftapp
  labels:
    app: giftapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: giftapp
  template:
    metadata:
      labels:
        app: giftapp
    spec:
      containers:
      - name: giftapp-container
        image: 411634473249.dkr.ecr.us-east-2.amazonaws.com/giftapp:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3060
      imagePullSecrets:
      - name: regcred

---
apiVersion: v1
kind: Service
metadata:
  name: gift-app-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3060
    protocol: TCP
  selector:
    app: giftapp